plot(HPCDataDateSlimmed$newdate, HPCDataDateSlimmed$Sub_metering_1, type= "n", xlab= "", ylab= "Energy sub metering")
lines(HPCDataDateSlimmed$newdate, HPCDataDateSlimmed$Sub_metering_1, col = "black")
lines(HPCDataDateSlimmed$newdate, HPCDataDateSlimmed$Sub_metering_2, col = "red")
lines(HPCDataDateSlimmed$newdate, HPCDataDateSlimmed$Sub_metering_3, col = "blue")
legend("topright", lty=c(1,1,1), col = c("black", "red", "blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), bg = "transparent", y.intersp = 0.3)
dev.copy(png, file = "Plot3.png", width = 480, height = 480)
dev.off()